apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
    app: {{ include "producer.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "producer.name" . }}
