image:
  repository: 2205experts/producer
  tag: latest

command:
  port: 5672
  server: rabbitmq
  message: "Hello"
  repeat: 30

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false


