apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
    app: {{ include "consumer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "consumer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "consumer.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 8080
        command: ["python", "consumer.py", "-p", "{{ .Values.command.port }}", "-s", "{{ .Values.command.server }}"]
